<!-- This is the navigation bar -->
<nav id="index_nav">
	<ul>
		<li><a href="index.php" title="home page" >Home</a></li>
		<li><a href="topic.php" title="topic page">Topic</a></li>
		<li><a href="quiz.php" title="form page">Quiz</a></li>
		<li><a href="enhancements.html" title="enhancements page">Enhancements</a></li>
		<li><a href="enhancements2.html" title="enhancements 2 page">Enhancements 2</a></li>
		<li><a href="phpenhancements.html" title="php enhacements page">PHP Enhancements</a></li>
		<li><a href="manage.php" title="home page">Manage</a></li>
	</ul>
</nav>
<hr />